name=vs_wrc058_fwdsrover
version=30.0.0
author=Vstone
license=MIT
maintainer=Vstone(infodesk@vstone.co.jp)
sentence=Arduino library for 4wdsrover X40A
paragraph=This library support VS-WRC058 that using for 4wdsrover X40A.
category=Device Control
url=https://www.vstone.co.jp/products/wheelrobot/4wdsrover_dl/index.html
architectures=VS-WRC058
depends=ros_lib
